### ISSUE TITLE
Create UI for administrative backend (ordinary website)

### ISSUE THREAD

**Issue by aiqueneldar** [aiqueneldar/participantcaller#11]
We need a standard page with menus and administration tasks that is used to setup events, participants, locations, etc as an administrative interface to the system.
Should be a usual page viewable from a standard computer screen browsing window.

**Comment by i3iorn** [comment]
@aiqueneldar I will close this one and use #12 as the main issue for UI because most of the code will be the same between all aspects of the interface.
