### ISSUE TITLE
Superfluous table

### ISSUE THREAD

**Issue by i3iorn** [aiqueneldar/participantcaller#17]
Going over the database model I realized that i think we have a table we would never need.

I can't think of a reason that we would ever need the Entity_Events table when we have the Entity_Event_Roles table. Whenever you connect an entity to an event it has to have a role. If we for some reason ever came up with a reason to connect an entity to an event we could have a role called "unassigned" or something.

I move that we remove the Entity_Events table unless you can think of a reason to define a relationship without a role @aiqueneldar.

**Comment by aiqueneldar** [comment]
I agree. Let's remove that table.
If we find that we need an entity without a role for an event, we'll just not set a role

**Comment by i3iorn** [comment]
Table remove from test database script.
