### ISSUE TITLE
Create database by design 

### ISSUE THREAD

**Issue by i3iorn** [aiqueneldar/participantcaller#2]
https://app.sqldbm.com/MySQL/Share/ECcg5CCRvWS5k0w4p2AzpEGFrngIE8md_DYjF4jNYw0

**Comment by i3iorn** [comment]
Have created most of the tables according to the design linked to test its validity with some testdata. Will give all tables some content and poke around to see that everything works as expected.

When I'm finished with populating the tables and have created some views that I expect will be needed I'll set up a testcase.

**Comment by i3iorn** [comment]
I am going to rewrite the database model to conform to 3NF. We were almost there but not quite.
https://en.wikipedia.org/wiki/Third_normal_form

**Comment by i3iorn** [comment]
Uploaded a database script including testdata, retarded testdata but there are rows in the tables.

**Comment by aiqueneldar** [comment]
Are we set on the design you created and showed me over at that DB diagram page?
I have no objections to it. It seems like a good schema. I will leave it to you to finish it since you seem to know what you are doing, and offer support and spitballing on DB design.

**Comment by i3iorn** [comment]
> 
> 
> Are we set on the design you created and showed me over at that DB diagram page?
> I have no objections to it. It seems like a good schema. I will leave it to you to finish it since you seem to know what you are doing, and offer support and spitballing on DB design.

Its setup for testing and we have a script which can create the schema again for any additional instances. We still need to evaluate what views and indexes we need to speed up development and production. Ill keep working on that.

**Comment by i3iorn** [comment]
Realized that thresholds are attributes and they should be saved among the other attributes in the database. Do you have any input @aiqueneldar? I suggest we remove the threshold related tables and change the constraints to refer to the attributes table instead.

**Comment by aiqueneldar** [comment]
Yes, the more generic the better and more future proof I would say. Remove them and include them as attributes.

**Comment by i3iorn** [comment]
Updated the database according to the new model.
