### ISSUE TITLE
Enable suitable ammount of logging

### ISSUE THREAD

**Issue by i3iorn** [aiqueneldar/participantcaller#3]
To continuously evaluate performance and spot bottlenecks we should figure out an apropriate amount of logging.

**Comment by i3iorn** [comment]
I have enabled a few log options by creating a new configuration file called "logging-enabled-group". It is based on the default aurora group except for that it has the following options set to 1:
general_log
log_queries_not_using_indexes
log_slave_updates
log_slow_admin_statements
log_slow_slave_statements

log_error_verbosity is set to 3 instead of 1 as per default.

**Comment by i3iorn** [comment]
@aiqueneldar can we spin up another database instance without additional cost or are we limited to one?

**Comment by aiqueneldar** [comment]
> @aiqueneldar can we spin up another database instance without additional cost or are we limited to one?

We can spin up another one. We pay for usage, not instances. So it always cost. But as long as we keep to maximum of 40 instances there is no more charge than should you use the same instance.

**Comment by aiqueneldar** [comment]
> I have enabled a few log options by creating a new configuration file called "logging-enabled-group". It is based on the default aurora group except for that it has the following options set to 1:
> general_log
> log_queries_not_using_indexes
> log_slave_updates
> log_slow_admin_statements
> log_slow_slave_statements
> 
> log_error_verbosity is set to 3 instead of 1 as per default.

This seem like a good idea for the Dev DB and env.
Is there any more to this ticket? otherwhise I move we close it.

**Comment by i3iorn** [comment]
At the moment I believe this to be sufficient.
