### ISSUE TITLE
Event API Functions

### ISSUE THREAD

**Issue by aiqueneldar** [aiqueneldar/participantcaller#5]
#4 is main ticket for this one.
This ticket is to implement a lambda functionality for API calls having to do with Events.

**Comment by i3iorn** [comment]
Event attribute values are not returned correctly when calling for a specific event ID.

The call:
https://2m9ajz98wd.execute-api.eu-west-1.amazonaws.com/Test/api/v1/event?eventid=1
returns these event attributes:
"eventattributes": [[1, "mi. Duis risus", null], [59, "auctor ullamcorper, nisl", null]]
it should be:
"eventattributes": [[1, "mi. Duis risus", 625], [59, "auctor ullamcorper, nisl", 927]]

**Comment by i3iorn** [comment]
The following columns are returned for all event locations:
eventID: 1
​​​​locationDescription: "nunc ac mattis ornare, lectus ante dictum mi,"
​​​​locationID: 1
​​​​locationName: "ultrices. Vivamus"
​​​​reusable: 0

It should be:
​​​​locationDescription: "nunc ac mattis ornare, lectus ante dictum mi,"
​​​​locationID: 1
​​​​locationName: "ultrices. Vivamus"
​​​​reusable: 0

No reason to return event id for all locations.

**Comment by i3iorn** [comment]
When calling all events you get an array of arrays. Expected result is an array of objects.
