### ISSUE TITLE
Attributes API Functions

### ISSUE THREAD

**Issue by aiqueneldar** [aiqueneldar/participantcaller#8]
#4 is the main ticket for this one.
This ticket is about implement Lambda functionality for API calls dealing with attributes.

**Comment by i3iorn** [comment]
Currently the api expects attribute ID's when a new event is created. We should allow both id's and attribute names or just attribute names if we want to allow for custom attributes, which the database is setup to support. 
This should not be high priority but I did not want to forget it either.

**Comment by i3iorn** [comment]
@aiqueneldar - If I want a list of all event attributes, do we need a new lambda function?
